steps:
- Variants
- TargQC
- Seq2C


variant_filtering:
  # If a variant is present in > [max_ratio] fraction AND > [max_sample_cnt] number of samples, AND not known,
  # it will be to be considered too common to be functional and filtered out.
  # Don't use it if the cohort is homogeneous! Use only for heterogeneous cohorts.
  max_ratio:      1.0
  max_sample_cnt: 5

  ###################
  ### vardict2mut ###
  min_freq_vardict2mut:  0.05 # -f
                              # When individual allele frequency (AF) is less than [min_freq], the variant is considered
                              # likely false poitive, unless it is actionable.
  min_hotspot_freq:   default # -F
                              # The minimum allele frequency hotspot somatic mutations, typically lower then -f.
                              # Default: 0.01 or half [min_freq], whichever is less.

  min_gmaf:            0.0025 # --gmaf
                              # When the GMAF is greater than specified, it's considered common SNP and filtered out.

  ###################
  ##### vcf2txt #####
  min_freq:     0.05    # -f
                        # When individual allele frequency (AF) is less than [min_freq], the variant is considered
                        # likely false poitive.

  min_p_mean:   5       # PMEAN.  -p   The minimum mean position in reads for variants.
  min_q_mean:   25      # QUAL.   -q   The minimum mean base quality phred score for variant.

  filt_depth:   0       # DP.     -D   The filtering total depth. The raw variant will be filtered on first place if the total depth is less then [filt_depth].
  filt_q_mean:  0       # QUAL.   -Q   The filtering mean position in reads for variants. The raw variant will be filtered on first place if the mean posititon is less then [filt_p_mean].
  filt_p_mean:  0       # PMEAN.  -P   The filtering mean base quality phred score for variants. The raw variant will be filtered on first place if the mean quality is less then [filt_q_mean].

  min_mq:       10      # MQ.     -M   The filtering mean mapping quality score for variants. The raw variant will be filtered if the mean mapping quality score is less then specified.
  min_vd:       2       # VD.     -V   The filtering variant depth. Variants with depth < [min_vd] will be considered false positive.

  signal_noise: 1.5     # SN.     -o   Signal/noise value.
  bias:         false   #         -b   Filter novel or dbSNP variants with strand bias "2;1" or "2;0" (BIAS field) and AF < 0.3.

  blacklist:
    genes:
      published: true
      abnormal_gc: true
      low_complexity: true
      repetitive_single_exome: true
      too_many_cosmic_mutations: true
    regions:
      abnormal_gc: true
      low_complexity: true
      hengs_universal_mask: true
      repeats: true


annotation:
  dbnsfp:
    skip-annotation: false
    annotations:
    - SIFT_score
    - Polyphen2_HVAR_score
    - Polyphen2_HVAR_pred
    - LRT_score
    - LRT_pred
    - MutationTaster_score
    - MutationTaster_pred
    - MutationAssessor_score
    - MutationAssessor_pred
    - FATHMM_score
    - Ensembl_geneid
    - Ensembl_transcriptid
    - Uniprot_acc
    - 1000Gp1_AC
    - 1000Gp1_AF
    - ESP6500_AA_AF
    - ESP6500_EA_AF

  dbsnp:
    all-annotations: False
    skip-annotation: False
    annotations:
    - SAO
    - VC
    - PM
    - HD
#    - KGPROD
#    - PH3
    - OM
    - CAF
    - COMMON
    - dbSNPBuildID
    - G5
    - CDA

  cosmic:
    all-annotations: False
    skip-annotation: False
    annotations:
    - CNT
    - AA
    - CDS
    - GENE

#  oncomine:
#    all-annotations: False
#    skip-annotation: False
#    annotations:
##    - om
#    - om_Cancer
#    - om_PATIENT
#    - om_MutClass
#    - om_MutClassPC

  clinvar:
    skip-annotation: False
    annotations:
    - CLNSIG  # Variant Clinical Significance, 0 - Uncertain significance, 1 - not provided, 2 - Benign, 3 - Likely benign, 4 - Likely pathogenic, 5 - Pathogenic, 6 - drug response, 7 - histocompatibility, 255 - other

  snpeff:  ## no "annotations" section here, always applied all annotations
    clinical_reporting: True    ## Canonical transcripts + output in HGVS notation
    cancer: False
    extra_options: ''
    skip-annotation: False

#  mongo:
#    all-annotations: True

#  custom_vcfs:
#    BALB_cJ_snps:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/BALB_cJ.mgp.v5.snps.dbSNP142.vcf.gz
#      annotations: DP, MQ, BALB_cJ_snps
#    BALB_cJ_indels:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/BALB_cJ.mgp.v5.indels.dbSNP142.normed.vcf.gz
#      annotations: DP, MQ, BALB_cJ_indels
#    C57BL_6NJ_snps:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/C57BL_6NJ.mgp.v5.snps.dbSNP142.vcf.gz
#      annotations: DP, MQ, C57BL_6NJ_snps
#    C57BL_6NJ_indels:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/C57BL_6NJ.mgp.v5.indels.dbSNP142.normed.vcf.gz
#      annotations: DP, MQ, C57BL_6NJ_indels
#    DBA_1J_snps:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/DBA_1J.mgp.v5.snps.dbSNP142.vcf.gz
#      annotations: DP, MQ, DBA_1J_snps
#    DBA_1J_indels:
#      path: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/DBA_1J.mgp.v5.indels.dbSNP142.normed.vcf.gz
#      annotations: DP, MQ, DBA_1J_indels

#  intersect_with:
#    BALB_cJ.snps:     /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/BALB_cJ.mgp.v5.snps.dbSNP142.vcf.gz
#    BALB_cJ.indels:   /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/BALB_cJ.mgp.v5.indels.dbSNP142.normed.vcf.gz
#    C57BL_6NJ.snps:   /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/C57BL_6NJ.mgp.v5.snps.dbSNP142.vcf.gz
#    C57BL_6NJ.indels: /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/C57BL_6NJ.mgp.v5.indels.dbSNP142.normed.vcf.gz
#    DBA_1J.snps:      /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/DBA_1J.mgp.v5.snps.dbSNP142.vcf.gz
#    DBA_1J.indels:    /ngs/reference_data/genomes/Mmusculus/mm10/variation/sanger_strain_specific/DBA_1J.mgp.v5.indels.dbSNP142.normed.vcf.gz

#  tracks:
#  - cpgIslandExt
#  - dgvMerged
#  - genomicSuperDups
#  - rptmk

  tsv_fields:
  - SAMPLE                        : Sample
  - CHROM                         : Chromosome
  - POS                           : Position
  - REF                           : REF
  - ALT                           : ALT
  - ID                            : ID
  - QUAL                          : QualityScore
  - DP                            : Depth
  - FILTER                        : Filter
  - dbSNPBuildID                  : dbSNPBuildID

  - dbNSFP_Ensembl_geneid         : EnsemblGeneID
  - dbNSFP_Ensembl_transcriptid   : EnsemblTranscriptID
  - dbNSFP_Uniprot_acc            : UniportAccNumber
  - "ANN[*].EFFECT"               : Effect
  - "ANN[*].IMPACT"               : Impact
  - "ANN[*].FEATURE"              : Feature_Type
  - "ANN[*].FEATUREID"            : Feature_ID
  - "ANN[*].ALLELE"               : Allele
  - "ANN[*].GENE"                 : Gene
  - "ANN[*].GENEID"               : Gene_ID
  - "ANN[*].BIOTYPE"              : BioType
  - "ANN[*].HGVS_C"               : HGVS.c
  - "ANN[*].HGVS_P"               : HGVS.p
  - "ANN[*].CDNA_POS"             : cDNA_pos
  - "ANN[*].CDNA_LEN"             : cDNA_len
  - "ANN[*].CDS_POS"              : CDS_pos
  - "ANN[*].CDS_LEN"              : CDS_len
  - "ANN[*].AA_POS"               : AA_pos
  - "ANN[*].AA_LEN"               : AA_len
  - "ANN[*].DISTANCE"             : Distance

  - CNT                           : CountInCosmic
  - AA                            : AminoAcidInCosmic
  - CDS                           : CDSInCosmic
#  - om_Cancer                     : OncomineCancer
#  - om_PATIENT                    : OncominePatient
#  - om_MutClass                   : OncomineMutClass
#  - om_MutClassPC                 : OncomineMutClassPC
  - "ANN[*].RANK"                 : Rank
  - BaseQRankSum                  : BaseQailityRankSum
  - FS                            : FischerScore
  - GC                            : GC
  - HaplotypeScore                : HaplotypeScore
  - HRun                          : HomopolymerRunSize
  - MQ                            : MappingQuality
  - MQRankSum                     : MQualityRankSum
  - MQ0                           : TotalMappingQualityZeroReads
  - QD                            : QualityByDepth
  - ReadPosRankSum                : ReadPosRankSum

  ## FORMAT fields for the sample  # * will be replaced with the tumor sample ID
  - GEN[*].GT                     : Genotype
  - GEN[*].PL                     : GenotypeLikelihoods
  - GEN[*].GQ                     : ConditionalGenotypeQuality
  - GEN[*].VD                     : VariantDepth
  - GEN[*].AF                     : AlleleFrequency
  - GEN[*].AO                     : AlleleObservationCount
  - GEN[*].QA                     : QualitySumForAltObservations
  - GEN[*].QR                     : QualitySumForRefObservations
  - GEN[*].RO                     : RefAlleleObservationCount

  ## dbsnp
  - SAO                           : VariantAlleleOrigin
  - AB                            : AlleleBalanceAtHeterozygousSites  # from GATK
  - VC                            : VariationClass
  - TYPE                          : AlleleType
  - PM                            : VariantIsPrecious
  - HD                            : PresentInDBGap
  - KGPROD                        : Has1000GenomeSubmission
  - PH3                           : HapMapValidated
  - OM                            : InOMIM
  - CAF                           : PerAlleleFrequencies
  - COMMON                        : CommonVariant
  - CLNSIG                        : ClinicalSignificance
  - G5                            : 5%MAFinPopulationsCAF
#  - GMAF                          : GlobalMinorAlleleFrequency
  # - CDA                         : InClinicalDiagnosticAssay
  - dbNSFP_SIFT_score             : SiftScore
  - dbNSFP_Polyphen2_HVAR_score   : PolyPhen2Score
  - dbNSFP_Polyphen2_HVAR_pred    : PolyPhen2Prediction
  - dbNSFP_LRT_score              : LrtScore
  - dbNSFP_LRT_pred               : LrtPrediction
  - dbNSFP_MutationTaster_score   : MutationTasterScore
  - dbNSFP_MutationTaster_pred    : MutationTasterPrediction
  - dbNSFP_MutationAssessor_score : MutationAssessorScore
  - dbNSFP_MutationAssessor_pred  : MutationAssessorPrediction
  - dbNSFP_FATHMM_score           : FATHMMScore
  - dbNSFP_1000Gp1_AC             : 1000GenomesAlleleCount
  - dbNSFP_1000Gp1_AF             : 1000GenomesAlleleFrequency
  - dbNSFP_ESP6500_AA_AF          : ESP6500AfricanAmericanAlleleFrequency
  - dbNSFP_ESP6500_EA_AF          : ESP6500EuropeanAmericanAlleleFrequency
  - cpgIslandExt                  : CPGIsland
  - genomicSuperDups              : GenomicDuplication
  - rptmk                         : KnownRepeat
  - dgvMerged                     : KnownCopyNumber
  - set                           : SourceVCF_forMergedRecInCombineVariants


quality_control:
  databases: ['dbsnp', 'cosmic', '1000genomes']
  novelty: ['known', 'novel', 'all']
  db_for_summary: cosmic
  variant_distribution_scale: 1000  ## in kilobases
  metrics: [
      'nEvalVariants', 'nSNPs', 'nInsertions', 'nDeletions',
      'nVariantsAtComp', 'compRate', 'nConcordant', 'concordantRate',
      'variantRate', 'variantRatePerBp', 'hetHomRatio', 'tiTvRatio']


coverage_reports:
  min_depth: 30  # regions with depth below this value will be flagged
  depth_thresholds: [1, 5, 10, 25, 50, 100, 500, 1000, 5000, 10000, 50000]
  padding: 200
  saturation: 'n'
  depthlist: 'auto'
  availablefeatures: [
     'percbases', 'saturation', 'specificity', 'coveragefreq',
     'coveragedistr', 'coveragestd', 'gcbias', 'coveragecorr']


verbose: True                 ## Prints tools' output
keep_intermediate: True       ## Keeps "work_dir" with intermediate files for each step
reuse_intermediate: False     ## If an intermediate VCFs exists and is not empty, skip a step and reuse the file
