resources:
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/snpEff.jar
    config: /ngs/RDI/PROGRAMS/snpEff/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/SnpSift.jar
  qualimap:
    path: ext_tools/qualimap/qualimap
  vcfannotate:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/vcfannotate
  java:
    path: /apps/java/x64/jdk1.7.0_45/bin/java
  python:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/anaconda/bin/python
  picard:
    path: ext_tools/picard/picard.jar
  samtools:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/samtools
  bedtools:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/bedtools
  perl:
    path: /usr/bin/perl
  tabix:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/tabix
  bgzip:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/bgzip
  gatk:
    path: /ngs/RDI/PROGRAMS/gatk/CancerAnalysisPackage-2014.3-24-g7dfb931/GenomeAnalysisTK.jar

genomes:
  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa
#    chr_lengths: /ngs/reference_data/genomes/Hsapiens/hg19/genome/human.hg19.genome

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/Cosmic-Coding_latest.vcf.gz
    1000genomes: /ngs/reference_data/genomes/Hsapiens/hg19/variation/1000G_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
    canonical_transcripts: /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/canonical_transcripts.txt

    exons:    /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/hg19/bed/CDS_RefSeq.bed

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    ruledir:                      /ngs/reference_data/genomes/Hsapiens/hg19/variation/rules
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    snpeffect_export_polymorphic: /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable_hotspot:           /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable_hotspot.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt

  GRCh37:
    seq: /ngs/reference_data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa

    dbsnp: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz
    cosmic: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/CosmicCodingMuts_v68.vcf  # /ngs/reference_data/genomes/Hsapiens/hg19/variation/cosmic-v68-hg19.vcf
    1000genomes: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/1000G_omni2.5.vcf
#    clinvar: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/clinvar_latest.vcf

    snpeff:
      reference: GRCh37.75
    canonical_transcripts: /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/canonical_transcripts.txt
#    polymorphic_variants: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/snpeffect_export_Polymorphic.txt
#    dbsnp_multi_mafs: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbSNP_multi_mafs_latest.txt

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    ruledir:                      /ngs/reference_data/genomes/Hsapiens/hg19/variation/rules
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt


snpeffect_export_polymorphic: /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
actionable_hotspot:           /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable_hotspot.txt

key_genes: /ngs/reference_data/genomes/Hsapiens/common/az_key_genes.txt
suppressors: /ngs/reference_data/genomes/Hsapiens/common/suppressors.txt
oncogenes: /ngs/reference_data/genomes/Hsapiens/common/oncogenes.txt
snpeff_transcripts: /ngs/reference_data/genomes/Hsapiens/common/canonical_transcripts.txt  # used if -canon is not set for snpEff

tricky_regions: ~/Dropbox/az/reference_data/tricky_regions/

queue: all.q

qsub_runner: scripts/runner_China.sh

smtp_host: '156.71.152.132'
