# /ngs/RDI/SCRIPTS/az.reporting

resources:
  python:
    path: /apps/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/bin/python
  perl:
    path: /usr/bin/perl
  java:
    path: /apps/java/x64/jdk1.7.0_45/bin/java
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff4.2/snpEff.jar
    config: /ngs/RDI/PROGRAMS/snpEff4.2/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff4.2/SnpSift.jar
#  gatk:
#    path: /ngs/RDI/PROGRAMS/GenomeAnalysisTK/GenomeAnalysisTK.jar
  vcf2txt:
    path: VarDict/vcf2txt.pl
  qualimap:
    path: ext_tools/qualimap/qualimap
  samtools:
    path: /apps/samtools/0.1.19/rhel6-x64/samtools
  bedtools:
    path: /apps/bedtools/2.16.2/x64/bin/bedtools
  tabix:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/tabix
  bgzip:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/bgzip
  picard:
    path: ext_tools/picard/picard.jar
  qsub:
    path: /apps/sge61/bin/lx24-amd64/qsub
  qdel:
    path: /apps/sge61/bin/lx24-amd64/qdel
  bwa:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/bwa
  bcftools:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/anaconda/bin/bcftools
  rscript:
    path: /apps/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/bin/Rscript

genomes:
  hg38:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq.all_features.hg38.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS.hg38.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg38-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38-noalt.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq.all_features.hg38-noalt.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS.hg38-noalt.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

  hg19-chr20:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19-chr20.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19-chr20.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19-chr20.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

queue: ngs.q

qsub_runner: scripts/runner_AP.sh
qsub_priority: 0

smtp_host: 'localhost'
