resources:
  gatk:
    jvm_opts: ["-Xms750m", "-Xmx2500m"]
    path: /usr/local/share/java/gatk/GenomeAnalysisTK.jar
    # path: /usr/local/share/java/gatk/GenomeAnalysisTKLite.jar
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx6g"]
    path: ext_tools/snpEff/snpEff.jar
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx6g"]
    path: ext_tools/snpEff/SnpSift.jar
  vcf2txt:
    path: VarDict/vcf2txt.pl
  qsub:
    path: tools/qsub.sh
  qdel:
    path: tools/qdel.sh
  vcf_merge:
    path: /usr/local/bin/vcf-merge
  picard:
    path: ext_tools/picard/picard.jar
  seqtk:
    path: /usr/local/bin/seqtk
  qualimap:
    path: ext_tools/qualimap/qualimap
  bedtools:
    path: /usr/local/bin/bedtools
  python:
    path: /Users/vlad/vagrant/venv/bin/python


genomes:
  hg19-chr21:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/seq/hg19-chr21.fa
    bwa:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/bwa/hg19-chr21.fa

    dbsnp:                    ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/dbsnp.vcf.gz
    dbsnp_multi_mafs:         ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    cosmic:                   ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/cosmic.vcf.gz
    clinvar:                  ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/clinvar_latest.vcf
    snpeff:
      reference: hg19

    features:                 ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/exons/all_features.bed  # canonical only
    bed_annotation_features:  ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/exons/all_features.bed  # all regions
    cds:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/exons/Seq2C_CDS.bed

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapien/hg19/tricky_regions/

  hg19-chr20:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr20/seq/hg19-chr20.fa
    bwa:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr20/bwa/hg19-chr20.fa

    snpeff:
      reference: hg19

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/tricky_regions/

  hg19:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa

    snpeff:
      reference: hg19

    features:                 ~/vagrant/reporting_suite/test/all_features_hg19.bed  # canonical only
    bed_annotation_features:  ~/vagrant/reporting_suite/test/all_features_hg19.bed  # all regions
    cds:                      ~/vagrant/TargQC/GeneAnnotation/RefSeq/hg19/Seq2C_CDS.bed

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/tricky_regions/

#    all_transcripts:          ~/Dropbox/az/reference_data/ref-transcripts_hg19.gtf

  hg38:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa

    dbsnp:                    ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/dbsnp.vcf.gz
    cosmic:                   ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/cosmic.vcf.gz
    oncomine:                 ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/oncomine.vcf

    features:                 ~/googledrive/az/reference_data/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed  # canonical only
    bed_annotation_features:  ~/googledrive/az/reference_data/Exons/RefSeq/RefSeq.all_features.hg38.bed  # all regions
    cds:                      ~/googledrive/az/reference_data/Exons/RefSeq/RefSeq_CDS.hg38.bed

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/tricky_regions/

#    all_transcripts:          ~/Dropbox/az/reference_data/ref-transcripts_hg19.gtf

queue: ngs.q

qsub_runner: scripts/runner_sequencial.sh

smtp_host: 'localhost'
