# /group/ngs/src/az.reporting

ld_library_path: /group/ngs/src/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/lib
# export LD_LIBRARY_PATH=/group/ngs/src/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/lib:$LD_LIBRARY_PATH

resources:
  python:
    path: /group/ngs/src/az.reporting/virtualenv/bin/python
    # path: /group/ngs/src/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/bin/python
    # path: /opt/az/local/psf/python/64_2.7.3/python
    # path: /opt/az/local/psf/python/2.7.8/Python-2.7.8/installdir/bin/python
  perl:
    path: /usr/bin/perl
  java:
    path: /usr/bin/java
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /group/ngs/src/snpEff4.2/snpEff.jar
    config: /group/ngs/src/snpEff4.2/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /group/ngs/src/snpEff4.2/SnpSift.jar
  gatk:
    path: /group/ngs/src/GenomeAnalysisTK/GenomeAnalysisTK.jar
  vcf2txt:
    path: VarDict/vcf2txt.pl
  vcfannotate:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/vcfannotate
  qualimap:
    path: ext_tools/qualimap/qualimap
  samtools:
    path: /group/ngs/src/samtools/samtools
  bedtools:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/bedtools
  igvtools:
    path: /opt/az/local/igvtools/2.3.32/IGVTools/igvtools.jar
  tabix:
    path: /opt/az/local/tabix/tabix-0.2.6/tabix
  bgzip:
    path: /opt/az/local/tabix/tabix-0.2.6/bgzip
  picard:
    path: ext_tools/picard/picard.jar
  qsub:
    path: /opt/az/adm/univa/bin/lx-amd64/qsub
  qdel:
    path: /opt/az/adm/univa/bin/lx-amd64/qdel
  bedops:
    path: /opt/az/local/bedops/bin/bedops
  fastqc:
    path: /opt/az/local/fastqc/11.3/FastQC/fastqc
  bwa:
    path: /opt/az/local/bwa/0.7.12/bwa-0.7.12/bwa
  seqtk:
    path: /group/ngs/src/bcbio-nextgen/0.9.5/rhel6-x64/bin/seqtk
  bamtools:
    path: /opt/az/local/bamtools/bamtools-master/bin/bamtools
  bammarkduplicates:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/bammarkduplicates
  bamdownsamplerandom:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/bamdownsamplerandom
  sambamba:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/sambamba
  bcftools:
    path: /group/ngs/src/bcbio-nextgen/0.9.6/rhel6-x64/bin/bcftools

genomes:
  hg38:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq.all_features.hg38.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS.hg38.bed

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg38/bed/tricky_regions

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg38-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bwa/hg38-noalt.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38-noalt.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq.all_features.hg38-noalt.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS.hg38-noalt.bed

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/tricky_regions

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  mm10:
    seq: /ngs/reference_data/genomes/Mmusculus/mm10/seq/mm10.fa
    bwa: /ngs/reference_data/genomes/Mmusculus/mm10/bwa/mm10.fa

    dbsnp: /ngs/reference_data/genomes/Mmusculus/mm10/variation/mm10-dbSNP-2013-09-12.vcf
    snpeff:
      reference: GRCm38.82

  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz
    # snpeff: /users/klpf990/snpeff/data  # /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/  # data dir path
    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19.bed

    az_exome:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tracks:
      cpgIslandExt: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/cpgIslandExt.bed       ## CpG Island
      dgvMerged: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/dgvMerged.bed          ## Copy Number Variants
      genomicSuperDups: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/genomicSuperDups.bed   ## Segmental Duplications
      rptmk: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/rptmk.bed              ## Repeats
      RNA_editing_AG: /ngs/reference_data/genomes/Hsapiens/hg19/variation/RNA_editing_AG.bed ## RNA Editing (RNA-Seq data)

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

  hg19-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/seq/hg19-noalt.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/bwa/hg19-noalt.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/CosmicCodingMuts_latest.vcf.gz
    1000genomes: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/1000G_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19-noalt/dbNSF/dbNSFP_latest.txt.gz
    # snpeff: /users/klpf990/snpeff/data  # /ngs/reference_data/genomes/Hsapiens/hg19-noalt/snpeff/  # data dir path
    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19-noalt/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19-noalt.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19-noalt/bed/Exons/RefSeq/RefSeq.all_features.hg19-noalt.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19-noalt/bed/Exons/RefSeq/RefSeq_CDS.hg19-noalt.bed

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/bed/Exome-AZ.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tracks:
      cpgIslandExt: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/tracks/cpgIslandExt.bed       ## CpG Island
      dgvMerged: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/tracks/dgvMerged.bed          ## Copy Number Variants
      genomicSuperDups: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/tracks/genomicSuperDups.bed   ## Segmental Duplications
      rptmk: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/tracks/rptmk.bed              ## Repeats
      RNA_editing_AG: /ngs/reference_data/genomes/Hsapiens/hg19-noalt/variation/RNA_editing_AG.bed ## RNA Editing (RNA-Seq data)

  hg19-chr20:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz
    # snpeff: /users/klpf990/snpeff/data  # /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/  # data dir path
    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19-chr20.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19-chr20.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19-chr20.bed

    az_exome:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tracks:
      cpgIslandExt: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/cpgIslandExt.bed       ## CpG Island
      dgvMerged: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/dgvMerged.bed          ## Copy Number Variants
      genomicSuperDups: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/genomicSuperDups.bed   ## Segmental Duplications
      rptmk: /ngs/reference_data/genomes/Hsapiens/hg19/tracks/rptmk.bed              ## Repeats
      RNA_editing_AG: /ngs/reference_data/genomes/Hsapiens/hg19/variation/RNA_editing_AG.bed ## RNA Editing (RNA-Seq data)

  GRCh37:
    seq: /ngs/reference_data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa

    features:                 /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exons/RefSeq/RefSeq_CDS.bed


snpeffect_export_polymorphic: /ngs/reference_data/genomes/Hsapiens/common/snpeffect_export_Polymorphic.txt
actionable_hotspot:           /ngs/reference_data/genomes/Hsapiens/common/actionable_hotspot.txt
ruledir:                      /ngs/reference_data/genomes/Hsapiens/common/rules
specific_mutations:           /ngs/reference_data/genomes/Hsapiens/common/specific_mutations.csv
key_genes:                    /ngs/reference_data/genomes/Hsapiens/common/az_key_genes.txt
suppressors:                  /ngs/reference_data/genomes/Hsapiens/common/suppressors.txt
oncogenes:                    /ngs/reference_data/genomes/Hsapiens/common/oncogenes.txt
last_critical_aa:             /ngs/reference_data/genomes/Hsapiens/common/last_critical_aa.txt

queue: batch.q

qsub_runner: scripts/runner_Waltham.sh
qsub_priority: 0

smtp_host: 'relay.astrazeneca.net'

