resources:
  gatk:
    jvm_opts: ["-Xms750m", "-Xmx2500m"]
    path: /usr/local/share/java/gatk/GenomeAnalysisTK.jar
    # path: /usr/local/share/java/gatk/GenomeAnalysisTKLite.jar
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx6g"]
    path: ext_tools/snpEff/snpEff.jar
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx6g"]
    path: ext_tools/snpEff/SnpSift.jar
  vcf2txt:
    path: VarDict/vcf2txt.pl
  qsub:
    path: tools/qsub.sh
  qdel:
    path: tools/qdel.sh
  vcf_merge:
    path: /usr/local/bin/vcf-merge
  picard:
    path: ext_tools/picard/picard.jar
  seqtk:
    path: /usr/local/bin/seqtk
  qualimap:
    path: ext_tools/qualimap/qualimap
  bedtools:
    path: /usr/local/bin/bedtools


genomes:
  hg19-chr21:
    seq:                      ~/Dropbox/az/reference_data/hg19-chr21/seq/hg19-chr21.fa
    bwa:                      ~/Dropbox/az/reference_data/hg19-chr21/bwa/hg19-chr21.fa

    dbsnp:                    ~/Dropbox/az/reference_data/hg19-chr21/variation/dbsnp.vcf.gz
    dbsnp_multi_mafs:         ~/Dropbox/az/reference_data/hg19/variation/dbSNP_multi_mafs_latest.txt
    cosmic:                   ~/Dropbox/az/reference_data/hg19-chr21/variation/cosmic.vcf.gz
    clinvar:                  ~/Dropbox/az/reference_data/hg19-chr21/variation/clinvar_latest.vcf
    snpeff:
      reference: hg19
    snpeff_transcripts:       ~/Dropbox/az/reference_data/canonical_transcripts/canonical_transcripts_hg19.txt

    features:                 ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/all_features.hg19-chr20.canon.bed  # canonical only
    bed_annotation_features:  ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/all_features.hg19-chr20.canon.bed  # all regions
    cds:                      ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/RefSeq_CDS.hg19-chr20.bed

    tricky_regions:           ~/Dropbox/az/reference_data/hg19/tricky_regions/

  hg19-chr20:
    seq:                      ~/Dropbox/az/reference_data/hg19-chr20/seq/hg19-chr20.fa
    bwa:                      ~/Dropbox/az/reference_data/hg19-chr20/bwa/hg19-chr20.fa

    snpeff:
      reference: hg19

    tricky_regions:           ~/Dropbox/az/reference_data/hg19/tricky_regions/

  hg19:
    seq:                      ~/Dropbox/az/reference_data/hg19/seq/hg19.fa

    snpeff:
      reference: hg19
    snpeff_transcripts:       ~/Dropbox/az/reference_data/canonical_transcripts/canonical_transcripts_hg19.txt

    features:                 ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/all_features.hg19.canon.bed  # canonical only
    bed_annotation_features:  ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/all_features.hg19.canon.bed  # all regions
    cds:                      ~/Dropbox/az/reference_data/GeneAnnotation/RefSeq/RefSeq_CDS.hg19.bed

    tricky_regions:           ~/Dropbox/az/reference_data/hg19/tricky_regions/

#    all_transcripts:          ~/Dropbox/az/reference_data/ref-transcripts_hg19.gtf

  hg38:
    seq:                      ~/Dropbox/az/reference_data/hg38/seq/hg38.fa

    dbsnp:                    ~/Dropbox/az/reference_data/hg38/variation/dbsnp.vcf.gz
    cosmic:                   ~/Dropbox/az/reference_data/hg38/variation/cosmic.vcf.gz
    oncomine:                 ~/Dropbox/az/reference_data/hg38/variation/oncomine.vcf

    snpeff_transcripts:       ~/Dropbox/az/reference_data/canonical_transcripts/canonical_transcripts_hg38.txt

    features:                 ~/Dropbox/az/reference_data/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed  # canonical only
    bed_annotation_features:  ~/Dropbox/az/reference_data/Exons/RefSeq/RefSeq.all_features.hg38.bed  # all regions
    cds:                      ~/Dropbox/az/reference_data/Exons/RefSeq/RefSeq_CDS.hg38.bed

    tricky_regions:           ~/Dropbox/az/reference_data/hg38/tricky_regions/

#    all_transcripts:          ~/Dropbox/az/reference_data/ref-transcripts_hg19.gtf

queue: ngs.q

qsub_runner: scripts/runner_sequencial.sh

smtp_host: 'localhost'
