resources:
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/snpEff.jar
    config: /ngs/RDI/PROGRAMS/snpEff/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/SnpSift.jar
  qualimap:
    path: /ngs/RDI/PROGRAMS/qualimap/qualimap
  vcfannotate:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/vcfannotate
  java:
    path: /apps/java/x64/jdk1.7.0_45/bin/java
  python:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/anaconda/bin/python
  picard:
    path: ext_tools/picard/picard.jar
  samtools:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/samtools
  bedtools:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/bedtools
  perl:
    path: /usr/bin/perl
  tabix:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/tabix
  bgzip:
    path: /home/klrl262/bcbio-nextgen/0.9.4/rhel6-x64/bin/bgzip
  gatk:
    path: /ngs/RDI/PROGRAMS/gatk/CancerAnalysisPackage-2014.3-24-g7dfb931/GenomeAnalysisTK.jar

genomes:
  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
#    chr_lengths: /ngs/reference_data/genomes/Hsapiens/hg19/genome/human.hg19.genome

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/Cosmic-Coding_latest.vcf.gz
    1000genomes: /ngs/reference_data/genomes/Hsapiens/hg19/variation/1000G_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
#    snpeff: /users/klpf990/snpeff/data  # /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/  # data dir path
#    snpeff_transcripts: /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/transcripts.txt  # used if -canon is not set for snpEff

    exons:    /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/hg19/bed/CDS_RefSeq.bed

    polymorphic_variants: /ngs/reference_data/genomes/Hsapiens/hg19/variation/snpeffect_export_Polymorphic.txt
    dbsnp_multi_mafs: /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt

  GRCh37:
    seq: /ngs/reference_data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa

    dbsnp: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz
    cosmic: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/CosmicCodingMuts_v68.vcf  # /ngs/reference_data/genomes/Hsapiens/hg19/variation/cosmic-v68-hg19.vcf
    1000genomes: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/1000G_omni2.5.vcf
#    clinvar: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/clinvar_latest.vcf

    snpeff:
      reference: GRCh37.75
#    polymorphic_variants: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/snpeffect_export_Polymorphic.txt
#    dbsnp_multi_mafs: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbSNP_multi_mafs_latest.txt

key_genes: /ngs/reference_data/genomes/Hsapiens/common/az_key_genes.txt

queue: all.q

qsub_runner: scripts/runner_China.sh

smtp_host: '156.71.152.132'
