resources:
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/snpEff.jar
    config: /ngs/RDI/PROGRAMS/snpEff/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff/SnpSift.jar
  gatk:
    path: /ngs/RDI/PROGRAMS/GenomeAnalysisTK/GenomeAnalysisTK.jar
  qualimap:
    path: ext_tools/qualimap/qualimap
  samtools:
    path: /apps/samtools/0.1.19/rhel6-x64/samtools
  bedtools:
    path: /apps/bedtools/2.16.2/x64/bin/bedtools
  perl:
    path: /usr/bin/perl
  java:
    path: /apps/java/x64/jdk1.7.0_45/bin/java
  python:
    path: /apps/bcbio-nextgen/0.9.5/rhel6-x64/anaconda/bin/python
  tabix:
    path: /apps/bcbio-nextgen/0.9.4/rhel6-x64/bin/tabix
  bgzip:
    path: /apps/bcbio-nextgen/0.9.4/rhel6-x64/bin/bgzip
  picard:
    path: ext_tools/picard/picard.jar
  qsub:
    path: /apps/sge61/bin/lx24-amd64/qsub
  qdel:
    path: /apps/sge61/bin/lx24-amd64/qdel
  bwa:
    path: /apps/bcbio-nextgen/0.9.4/rhel6-x64/bin/bwa
  sambamba:
    path: /apps/bcbio-nextgen/0.9.4/rhel6-x64/bin/sambamba

genomes:
  hg38:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbsnp_latest.vcf
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/clinvar.vcf
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicV72CodingMuts.vcf
    snpeff:
      reference: hg38

    exons:    /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/hg38/bed/CDS_RefSeq.bed

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
#    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/Compendia.MS7.Hotspot.txt

  hg38-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbsnp_latest.vcf
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/clinvar.vcf
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/CosmicV72CodingMuts.vcf
    snpeff:
      reference: hg38

    exons:    /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/hg38/bed/CDS_RefSeq.bed

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
#    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/Compendia.MS7.Hotspot.txt

  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa
    # chr_lengths: /ngs/reference_data/genomes/Hsapiens/hg19/genome/human.hg19.genome

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/Cosmic-Coding_latest.vcf  # /ngs/reference_data/genomes/Hsapiens/hg19/variation/cosmic-v68-hg19.vcf
    1000genomes: /ngs/reference_data/genomes/Hsapiens/hg19/variation/1000G_latest.vcf
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19

    exons:    /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/hg19/bed/CDS_RefSeq.bed

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

  GRCh37:
    seq: /ngs/reference_data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbsnp_latest.vcf
    cosmic:      /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/CosmicCodingMuts_latest.vcf  # /ngs/reference_data/genomes/Hsapiens/hg19/variation/cosmic-v68-hg19.vcf
    1000genomes: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/1000G_omni2.5.vcf
    clinvar:     /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/clinvar_latest.vcf
    oncomine:    /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/oncomine/mutation_details.vcf
    snpeff:
      reference: GRCh37.75

    exons:    /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exons/Exons.with_genes.bed
    az_exome: /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exome-AZ.bed
    refseq:   /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/CDS_RefSeq.bed

    polymorphic_variants:         /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/snpeffect_export_Polymorphic.txt
    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt


snpeffect_export_polymorphic: /ngs/reference_data/genomes/Hsapiens/common/snpeffect_export_Polymorphic.txt
actionable_hotspot:           /ngs/reference_data/genomes/Hsapiens/common/actionable_hotspot.txt
ruledir:                      /ngs/reference_data/genomes/Hsapiens/common/rules
key_genes:                    /ngs/reference_data/genomes/Hsapiens/common/az_key_genes.txt
suppressors:                  /ngs/reference_data/genomes/Hsapiens/common/suppressors.txt
oncogenes:                    /ngs/reference_data/genomes/Hsapiens/common/oncogenes.txt
specific_mutations:           /ngs/reference_data/genomes/Hsapiens/common/specific_mutations.csv
#canonical_transcripts:        /ngs/reference_data/genomes/Hsapiens/common/canonical_transcripts.txt
snpeff_transcripts:           /ngs/reference_data/genomes/Hsapiens/common/canonical_transcripts.txt

queue: ngs.q

qsub_runner: scripts/runner_AP.sh
qsub_priority: 0

smtp_host: 'localhost'
