# /ngs/RDI/SCRIPTS/az.reporting

ld_library_path: /group/ngs/src/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/lib

resources:
  python:
    path: /apps/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/bin/python
  perl:
    path: /usr/bin/perl
  java:
    path: /apps/java/x64/jdk1.7.0_45/bin/java
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff4.2/snpEff.jar
    config: /ngs/RDI/PROGRAMS/snpEff4.2/snpEff.config
  snpsift:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
    path: /ngs/RDI/PROGRAMS/snpEff4.2/SnpSift.jar
  gatk:
    path: /ngs/RDI/PROGRAMS/GenomeAnalysisTK/GenomeAnalysisTK.jar
  vcf2txt:
    path: VarDict/vcf2txt.pl
  qualimap:
    path: ext_tools/qualimap/qualimap
  samtools:
    path: /apps/samtools/0.1.19/rhel6-x64/samtools
  bedtools:
    path: /apps/bedtools/2.16.2/x64/bin/bedtools
  tabix:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/tabix
  bgzip:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/bgzip
  picard:
    path: ext_tools/picard/picard.jar
  qsub:
    path: /apps/sge61/bin/lx24-amd64/qsub
  qdel:
    path: /apps/sge61/bin/lx24-amd64/qdel
  bwa:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/bwa
  sambamba:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/bin/sambamba
  bcftools:
    path: /apps/bcbio-nextgen/0.9.6/rhel6-x64/anaconda/bin/bcftools
  rscript:
    path: /apps/bcbio-nextgen/0.9.7/rhel6-x64/anaconda/bin/Rscript

genomes:
  hg38:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq.all_features.hg38.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS.hg38.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg38/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg38-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38-noalt.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq.all_features.hg38-noalt.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS.hg38-noalt.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

  hg19-chr20:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19-chr20.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19-chr20.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19-chr20.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt
    splice:                       /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/SPLICE.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

#  GRCh37:
#    seq: /ngs/reference_data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
#    bwa: /ngs/reference_data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa
#
#    dbsnp:       /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/dbsnp_latest.vcf
#    cosmic:      /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/CosmicCodingMuts_latest.vcf  # /ngs/reference_data/genomes/Hsapiens/hg19/variation/cosmic-v68-hg19.vcf
#    1000genomes: /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/1000G_omni2.5.vcf
#    clinvar:     /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/clinvar_latest.vcf
#    oncomine:    /ngs/reference_data/genomes/Hsapiens/GRCh37/variation/oncomine/mutation_details.vcf
#    snpeff:
#      reference: GRCh37.75
#
#    exons:    /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exons/Exons.with_genes.bed
#    az_exome: /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/Exome-AZ.bed
#    refseq:   /ngs/reference_data/genomes/Hsapiens/GRCh37/bed/CDS_RefSeq.bed
#
#    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt
#    filter_common_snp:            /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_snp.txt
#    filter_common_artifacts:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/filter_common_artifacts.txt
#    actionable:                   /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/actionable.txt
#    compendia_ms7_hotspot:        /ngs/reference_data/genomes/Hsapiens/hg19/variation/cancer_informatics/Compendia.MS7.Hotspot.txt


snpeffect_export_polymorphic: /ngs/reference_data/genomes/Hsapiens/common/snpeffect_export_Polymorphic.txt
actionable_hotspot:           /ngs/reference_data/genomes/Hsapiens/common/actionable_hotspot.txt
ruledir:                      /ngs/reference_data/genomes/Hsapiens/common/rules
key_genes:                    /ngs/reference_data/genomes/Hsapiens/common/az_key_genes.txt
suppressors:                  /ngs/reference_data/genomes/Hsapiens/common/suppressors.txt
oncogenes:                    /ngs/reference_data/genomes/Hsapiens/common/oncogenes.txt
specific_mutations:           /ngs/reference_data/genomes/Hsapiens/common/specific_mutations.csv
last_critical_aa:             /ngs/reference_data/genomes/Hsapiens/common/last_critical_aa.txt
crapomedir:                   /ngs/reference_data/genomes/Hsapiens/common/crapome

queue: ngs.q

qsub_runner: scripts/runner_AP.sh
qsub_priority: 0

smtp_host: 'localhost'
