filter_reject: true
genome: {cosmic: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/variation/cosmic-v68-hg19.vcf,
  dbsnp: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/variation/dbsnp_132.vcf,
  name: hg19, seq: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/seq/hg19.fa,
  snpeff: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/snpeff}
keep_intermediate: true
log: /Users/vladsaveliev/vagrant/variantannotation/work/S1_log.txt
name: S1
output_dir: /Users/vladsaveliev/vagrant/variantannotation
parallel: false
quality_control:
  database_vcfs: {cosmic: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/variation/cosmic-v68-hg19.vcf,
    dbsnp: /Users/vladsaveliev/vagrant/bcbio-nextgen/tests/data/genomes/hg19/variation/dbsnp_132.vcf}
  databases: [dbsnp, cosmic]
  metrics: [nEvalVariants, nSNPs, nInsertions, nDeletions, nVariantsAtComp, compRate,
    nConcordant, concordantRate, variantRate, variantRatePerBp, hetHomRatio, tiTvRatio]
  novelty: [all, known, novel]
resources:
  bcbfools: {path: /Users/vladsaveliev/bin/bcftools/bcftools}
  gatk:
    jvm_opts: [-Xms750m, -Xmx2500m]
    path: /usr/local/share/java/gatk/GenomeAnalysisTK.jar
  plot_vcfstats: {path: /Users/vladsaveliev/bin/bcftools/plot-vcfstats}
  snpeff:
    jvm_opts: [-Xms750m, -Xmx6g]
    path: /usr/local/share/java/snpEff/snpEff.jar
  snpsift:
    jvm_opts: [-Xms750m, -Xmx6g]
    path: /usr/local/share/java/snpEff/SnpSift.jar
reuse_intermediate: true
split_samples: false
vcf: /Users/vladsaveliev/vagrant/variantannotation/work/S1.vcf
verbose: true
work_dir: /Users/vladsaveliev/vagrant/variantannotation/work
